### ISSUE TITLE
ADB Install stuck...

### ISSUE THREAD

**Issue by ttv20** [pylerSM/XInstaller#23]
when I try to install APK by ADB its stuck [adb install APKFILE]
I try from several computers
when i unmark the module and reboot is working again

I Have THL 5000 (Chinese) 
AOSP ROM
Android 4.4.2
Xposed 2.6.1

Thank you

**Comment by pylerSM** [comment]
Did you enable option (Disable) Installing in background? But... it should work for adb still.. even if option is enabled.

if (isModuleEnabled() && installBackground) {
					if (Binder.getCallingUid() == Common.ROOT_UID) {
						param.setResult(null);
					}
				}

basically it stops installations if option is enabled and if app calls commands as root.
