### ISSUE TITLE
No tutorial.

### ISSUE THREAD

**Issue by easyaspi314** [pylerSM/XInstaller#24]
There is no way you would know what to do with some of the tweaks. How would I know that I needed to click on the package name? 

Add a subtitle on the prefs with an explaination of what to do. Fixed.

**Comment by pylerSM** [comment]
Soon.

**Comment by easyaspi314** [comment]
I am working on this, but it will need to be translated.

**Comment by easyaspi314** [comment]
I added a few in #27.

**Comment by pylerSM** [comment]
I wrote something some time ago: http://www22.zippyshare.com/v/BOegtyJP/file.html
