### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by pylerSM** [pylerSM/XInstaller#34]
http://forum.xda-developers.com/showpost.php?p=63847192&postcount=881

@easyaspi314 ?

**Comment by easyaspi314** [comment]
On it. The text colors for the preference headers is a (*sigh*) private API.
I am trying out the light Material theme with teal/pink like the icon, yet not really changing the Holo version.. I also updated the help icon to both Holo and Material versions.

**Comment by easyaspi314** [comment]
I also fixed the crash, I am just working on the footer because when I change it to the light theme, the text is black,

**Comment by easyaspi314** [comment]
I am adding RTL support in the 2 layouts we have. :globe_with_meridians: 
Just need to fix an InflateException.

By the way, [Cracker](http://repo.xposed.info/module/io.github.mthli.cracker): Amazing.

**Comment by easyaspi314** [comment]
Fixed in my recent commit

**Comment by pylerSM** [comment]
Great
