### ISSUE TITLE
small(maybe) problem on cm11

### ISSUE THREAD

**Issue by eebssk1** [pylerSM/XInstaller#37]
Sometimes after boot is completed about four minutes, it loses effect. I need to re-launch the program, disable and re-enable module ("Enable Module" is still in the open position) in order to fix this problem.
Sometimes even if the above problem does not occur after I hibernate application with greenify( xposed mode) about twice, this problem also occurs. after I use the above method, the problem will be fixed, and will not happen again after this boot-time.
It means that I need to manually re-enable it after booting to make it run properly. But this is not the best way (if you hide the launch icon?)
Please fix this problem
Cyanogen 11
768m RAM

translated by google

**Comment by easyaspi314** [comment]
So you are hibernating this in Greenify? That might be the issue. Try
adding it to the whitelist.

– Devin Hussey

**Comment by eebssk1** [comment]
i  found it is XPosed framework's issue now
CLOSED
